[build]
  functions = "functions"
  publish = "public"

[[redirects]]
  from = "/generate-questions"
  to = "/.netlify/functions/server/generate-questions"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/server/health"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
